name: WDOG Watcher
on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      SOLANA_RPC: ${{ secrets.SOLANA_RPC }}         # <-- ton endpoint Helius
      WDOG_MINT: ${{ secrets.WDOG_MINT }}
      TARGET_ADDRESS: ${{ secrets.TARGET_ADDRESS }}
      WDOG_ALERT_MIN: ${{ secrets.WDOG_ALERT_MIN }}
      SOL_ALERT_MIN: ${{ secrets.SOL_ALERT_MIN }}
      LOOKBACK_TX: ${{ secrets.LOOKBACK_TX }}
      WDOG_TOP_WALLET: ${{ secrets.WDOG_TOP_WALLET }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Sanity check (masqué)
        run: |
          node -e "console.log('SOLANA_RPC present =', !!process.env.SOLANA_RPC); console.log('TARGET_ADDRESS length =', (process.env.TARGET_ADDRESS||'').length);"

      - name: Install deps
        working-directory: Snipe-Wdog
        run: npm ci || npm i

      - name: Run WDOG watcher
        working-directory: Snipe-Wdog
        run: node watch-wdog.js
