name: WDOG Watch

on:
  schedule:
    - cron: "*/30 * * * *"   # toutes les 30 min
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install
        run: npm ci || npm i

      - name: Run watcher
        env:
          SOLANA_RPC: ${{ secrets.SOLANA_RPC }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          WDOG_MINT: ${{ secrets.WDOG_MINT }}
          LOOKBACK_TX: "40"
          WDOG_ALERT_MIN: "1000000"
          SOL_ALERT_MIN: "200"
        run: npm start
